1. Create a 5x7 NumPy array filled with random numbers. Use fancy indexing to access the following entries (row, col): (1,3),(4,5),(3,2), and (0,6).

In [1]:
import numpy as np
x=np.random.randint(100, size=(5, 7))
print(x)

[[32 53 30 94 81 33 78]
 [61 30 77 90 58 51  3]
 [47 68 24  8  3  1 42]
 [ 7 10 82 92 48 88 23]
 [50 63 34 69 25 31 49]]


In [2]:
[x[1, 3], x[4, 5], x[3, 2], x[0, 6]]

[90, 31, 82, 78]

2. Explain what np.newaxis does and provide an example of how one might use it.

In [3]:
# Np.newaxis is used to increase the dimension of an existing array in an interval of one.
# For example, if you have an 1D array you can use this to make it into 2D array.
A = np.array([2, 0, 2, 2])
A[:, np.newaxis]

array([[2],
       [0],
       [2],
       [2]])

3. What sorting method does np.sort use and what is its runtime complexity (Big-O)? What does this mean?

In [4]:
#Np.sort by default follows a quicksort algorithm. The runtime complexity (Big-O) is O[NlogN]. 
#A algorithm that calculates the time it takes for a string of code to run.

4. Given the following NumPy array: [4,1,5,2,7,3], what are the indices of the sorted order?

In [5]:
npind = np.array([4,1,5,2,7,3])
i = np.argsort(npind)
print(i)

[1 3 5 0 2 4]


5. Using the array from #1, sort the columns.

In [6]:
x.sort(axis=0)
x

array([[ 7, 10, 24,  8,  3,  1,  3],
       [32, 30, 30, 69, 25, 31, 23],
       [47, 53, 34, 90, 48, 33, 42],
       [50, 63, 77, 92, 58, 51, 49],
       [61, 68, 82, 94, 81, 88, 78]])

6. Using the array from #1, sort the rows.

In [7]:
x.sort(axis=1)
x

array([[ 1,  3,  3,  7,  8, 10, 24],
       [23, 25, 30, 30, 31, 32, 69],
       [33, 34, 42, 47, 48, 53, 90],
       [49, 50, 51, 58, 63, 77, 92],
       [61, 68, 78, 81, 82, 88, 94]])

7. How is a structured array different from a traditional NumPy array, and why might one use it?

In [8]:
#Structured array has the capability to store both compound and heterogeneous data, 
#while traditional NumPy array can only store heterogeneous data.
#Structured array is useful when you are trying to group data of different types and sizes together.

8. Complete the following exercise – activity created by Guilherme Samora.

a. Import two datasets: cars1 and cars2.

In [9]:
#import packages
import pandas as pd
#import and read cav file
cars1 = pd.read_csv('cars1.csv')
cars2 = pd.read_csv('cars2.csv')

b. Print the top five rows of each.

In [10]:
cars1.head()

mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0  18.0          8           307        130    3504          12.0     70   
1  15.0          8           350        165    3693          11.5     70   
2  18.0          8           318        150    3436          11.0     70   
3  16.0          8           304        150    3433          12.0     70   
4  17.0          8           302        140    3449          10.5     70   

   origin                        car  Unnamed: 9  Unnamed: 10  Unnamed: 11  \
0       1  chevrolet chevelle malibu         NaN          NaN          NaN   
1       1          buick skylark 320         NaN          NaN          NaN   
2       1         plymouth satellite         NaN          NaN          NaN   
3       1              amc rebel sst         NaN          NaN          NaN   
4       1                ford torino         NaN          NaN          NaN   

   Unnamed: 12  Unnamed: 13  
0          NaN          NaN  
1          NaN          NaN  
2          NaN          NaN  
3          NaN          NaN  
4          NaN          NaN

In [11]:
cars2.head()

mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0  33.0          4            91         53    1795          17.4     76   
1  20.0          6           225        100    3651          17.7     76   
2  18.0          6           250         78    3574          21.0     76   
3  18.5          6           250        110    3645          16.2     76   
4  17.5          6           258         95    3193          17.8     76   

   origin                 car  
0       3         honda civic  
1       1      dodge aspen se  
2       1   ford granada ghia  
3       1  pontiac ventura sj  
4       1       amc pacer d/l

c. Clean cars1 removing any unnamed columns (hint: loc might be helpful)

In [12]:
cars1 = cars1.loc[:, ~cars1.columns.str.contains('^Unnamed')]

d. How many observations exist in each dataset?

In [13]:
cars1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198 entries, 0 to 197
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           198 non-null    float64
 1   cylinders     198 non-null    int64  
 2   displacement  198 non-null    int64  
 3   horsepower    198 non-null    object 
 4   weight        198 non-null    int64  
 5   acceleration  198 non-null    float64
 6   model         198 non-null    int64  
 7   origin        198 non-null    int64  
 8   car           198 non-null    object 
dtypes: float64(2), int64(5), object(2)
memory usage: 14.0+ KB


In [14]:
cars2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           200 non-null    float64
 1   cylinders     200 non-null    int64  
 2   displacement  200 non-null    int64  
 3   horsepower    200 non-null    object 
 4   weight        200 non-null    int64  
 5   acceleration  200 non-null    float64
 6   model         200 non-null    int64  
 7   origin        200 non-null    int64  
 8   car           200 non-null    object 
dtypes: float64(2), int64(5), object(2)
memory usage: 14.2+ KB


e. Join cars1 and cars2 into one dataframe.

In [15]:
cars = pd.concat([cars1, cars2], axis=0)

f. Let’s add a column called owners consisting of random numbers from 15,000 to 73,000.

In [16]:
cars['owners'] = np.random.randint(15000, 73000, cars.shape[0])

g. Add it to the cars dataframe.

In [17]:
cars

mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0    18.0          8           307        130    3504          12.0     70   
1    15.0          8           350        165    3693          11.5     70   
2    18.0          8           318        150    3436          11.0     70   
3    16.0          8           304        150    3433          12.0     70   
4    17.0          8           302        140    3449          10.5     70   
..    ...        ...           ...        ...     ...           ...    ...   
195  27.0          4           140         86    2790          15.6     82   
196  44.0          4            97         52    2130          24.6     82   
197  32.0          4           135         84    2295          11.6     82   
198  28.0          4           120         79    2625          18.6     82   
199  31.0          4           119         82    2720          19.4     82   

     origin                        car  owners  
0         1  chevrolet chevelle malibu   48772  
1         1          buick skylark 320   64146  
2         1         plymouth satellite   28874  
3         1              amc rebel sst   22629  
4         1                ford torino   42097  
..      ...                        ...     ...  
195       1            ford mustang gl   17527  
196       2                  vw pickup   38686  
197       1              dodge rampage   19032  
198       1                ford ranger   59176  
199       1                 chevy s-10   51916  

[398 rows x 10 columns]

h. Print the last five rows of the dataset.

In [18]:
cars.tail()

mpg  cylinders  displacement horsepower  weight  acceleration  model  \
195  27.0          4           140         86    2790          15.6     82   
196  44.0          4            97         52    2130          24.6     82   
197  32.0          4           135         84    2295          11.6     82   
198  28.0          4           120         79    2625          18.6     82   
199  31.0          4           119         82    2720          19.4     82   

     origin              car  owners  
195       1  ford mustang gl   17527  
196       2        vw pickup   38686  
197       1    dodge rampage   19032  
198       1      ford ranger   59176  
199       1       chevy s-10   51916

i. Which car has the min mpg?

In [19]:
print(cars[cars.mpg == cars.mpg.min()])

    mpg  cylinders  displacement horsepower  weight  acceleration  model  \
28  9.0          8           304        193    4732          18.5     70   

    origin       car  owners  
28       1  hi 1200d   55939  


j. Which car has the max horsepower?

In [20]:
#has to drop all of the '?' to get the max horsepower
cars3 = cars[cars.horsepower != "?"]

In [21]:
cars3

mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0    18.0          8           307        130    3504          12.0     70   
1    15.0          8           350        165    3693          11.5     70   
2    18.0          8           318        150    3436          11.0     70   
3    16.0          8           304        150    3433          12.0     70   
4    17.0          8           302        140    3449          10.5     70   
..    ...        ...           ...        ...     ...           ...    ...   
195  27.0          4           140         86    2790          15.6     82   
196  44.0          4            97         52    2130          24.6     82   
197  32.0          4           135         84    2295          11.6     82   
198  28.0          4           120         79    2625          18.6     82   
199  31.0          4           119         82    2720          19.4     82   

     origin                        car  owners  
0         1  chevrolet chevelle malibu   48772  
1         1          buick skylark 320   64146  
2         1         plymouth satellite   28874  
3         1              amc rebel sst   22629  
4         1                ford torino   42097  
..      ...                        ...     ...  
195       1            ford mustang gl   17527  
196       2                  vw pickup   38686  
197       1              dodge rampage   19032  
198       1                ford ranger   59176  
199       1                 chevy s-10   51916  

[392 rows x 10 columns]

In [22]:
cars3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 392 entries, 0 to 199
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           392 non-null    float64
 1   cylinders     392 non-null    int64  
 2   displacement  392 non-null    int64  
 3   horsepower    392 non-null    object 
 4   weight        392 non-null    int64  
 5   acceleration  392 non-null    float64
 6   model         392 non-null    int64  
 7   origin        392 non-null    int64  
 8   car           392 non-null    object 
 9   owners        392 non-null    int64  
dtypes: float64(2), int64(6), object(2)
memory usage: 33.7+ KB


In [23]:
#df["a"] = pd.to_numeric(df["a"])
#horsepower was an obj and needs to be changed into int to find max
cars3["horsepower"] = pd.to_numeric(cars3["horsepower"])


<ipython-input-23-848bec8e56eb>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cars3["horsepower"] = pd.to_numeric(cars3["horsepower"])


In [24]:
print(cars3[cars3.horsepower == cars3.horsepower.max()])

      mpg  cylinders  displacement  horsepower  weight  acceleration  model  \
116  16.0          8           400         230    4278           9.5     73   

     origin                 car  owners  
116       1  pontiac grand prix   24282  
